### ISSUE TITLE
Hostname in certificate didn't match.

### ISSUE THREAD

**Issue by NanuPhoenix** [ncalexan/fxa-custom-server-addon#2]
Hi,

I'm currently unable to use the sync with my hosted server, a quick look in log cat reveals the following issue:

javax.net.ssl.SSLException: hostname in certificate didn't match:

I have certificates set up for a number of subdomains on my server, browsers are able to distinguish between each successfully, but it would appear Android carries out a DNS lookup on the syncserver hostname and then queries the certificate against the default host returned, rather than the syncserver subdomain, resulting in an error.

Apparently, this can be overcome using SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER as detailed [here] (http://stackoverflow.com/questions/25356739/javax-net-ssl-sslexception-hostname-in-certificate-didnt-match-android) though I have no idea if this remains secure or if indeed it can be implemented.

**Comment by ncalexan** [comment]
Hi!  Sorry I never replied to this.  This addon is deprecated now, so I won't be addressing this.
