### ISSUE TITLE
Add to desktop firefox too?

### ISSUE THREAD

**Issue by orencio** [ncalexan/fxa-custom-server-addon#3]
Hello, thank you for your extension.
Is it possible to install this extension on Firefox desktop version? In this versions it isn't possible to change server too.

**Comment by pochy-ja** [comment]
Long time ago I write a addon for myself, the addon change the prefs of custom sync and firefox accounts in desktop version, at this moment it supports the new pref for firefox 42, maybe this help, more in https://addons.mozilla.org/es/firefox/addon/custom-sync-fxa/

**Comment by ncalexan** [comment]
This addon is deprecated now, so I won't be addressing this.  New documentation should be up at http://docs.services.mozilla.com/ shortly, which makes this process more like Desktop.  @pochy-ja, you might consider updating your addon to help Fennec users too...

**Comment by pochy-ja** [comment]
Sure, I go to investigate about how can I do this.
