### ISSUE TITLE
it does not work with Owncloud Sync?

### ISSUE THREAD

**Issue by gerroon** [ncalexan/fxa-custom-server-addon#4]
Hi

I am trying to get this working with Owncloud FF sync https://github.com/owncloud/mozilla_sync. My Iceweasel syncs fine with my server but I cant get the same account and the same url work with it this addon. I am not sure if this is a addon issue or OC issue. 

This is what OC gives me when the Android addon tries to sign in.
{"reqId":"b7aef1a7e502f7850a1735a6cbc674da","remoteAddr":"192.xx.xx.xx","app":"mozilla_sync","message":"remote.php#19 __construct():  URL: Illegal version account found.","level":3,"time":"2015-05-30T03:27:58+00:00"}

My url for the for both the account and the sync is same which is what OC setup provides.

I am using Fennec 38.0.1

thanks

**Comment by gerroon** [comment]
Btw the Logcat says that

"FxaAccountSetUpTas: Got Failure
fxaaccountabstractsetupactivity got exception showing error message"

That is pretty much it I do not see anything else except some illegal character path at index 86: file://....... ... but it is not clear which addon since it is hashed. It might not be related

thanks

**Comment by ncalexan** [comment]
On Fri, May 29, 2015 at 8:31 PM, gerroon <notifications@github.com> wrote:

> Hi
>
> I am trying to get this working with Owncloud FF sync
> https://github.com/owncloud/mozilla_sync. My Iceweasel syncs fine with my
> server but I cant get the same account and the same url work with it this
> addon. I am not sure if this is a addon issue or OC issue.
>
> This is what OC gives me when the Android addon tries to sign in.
> {"reqId":"b7aef1a7e502f7850a1735a6cbc674da","remoteAddr":"192.xx.xx.xx","app":"mozilla_sync","message":"remote.php#19
> __construct(): URL: Illegal version account
> found.","level":3,"time":"2015-05-30T03:27:58+00:00"}
>
> My url for the for botht the account and the sync is same which is what OC
> setup provides.
>
The addon is only for use with custom FxA + Sync 1.5 stacks.  Owncloud only
provides a Sync 1.1 stack.  You don't need the addon at all to use Sync 1.1
in Firefox for Android; you just need to connect to an "Old Sync" account.
Try Android Settings > Accounts  > Add Account > Firefox Sync (deprecated)
and pair with your desktop.  I can't find a documentation link right now.

You should be aware that Legacy Sync 1.1 support will be going away from
Firefox entirely in the very near future, see the deprecation blog post:
https://blog.mozilla.org/services/2015/02/03/legacy-sync-migration/

**Comment by gerroon** [comment]
HI
Thanks for the follow up. I understand the issue better now. However the solution was much easier than it looks after you pointed out the problem. Appearantly there is an account that one can create using Android account system called "Firefox Sync Deprecated" which just takes care of the whole issue once one has a working OC server.
