### ISSUE TITLE
Not syncing in Nginx + Gunicorn

### ISSUE THREAD

**Issue by magarto** [ncalexan/fxa-custom-server-addon#5]
Hi!

I made my own Firefox Sync token server v 1.5 and I can sync Firefox Desktop using my server url but I can't sync it using this addon for Android Firefox (tried in Android 5.0 and Android 4.4 with two devices)
I followed this guide: https://docs.services.mozilla.com/howtos/run-sync-1.5.html
I followed your setprop and logcat commands to send you the log but it doesn't show anything.

My Firefox Sync token server configuration is:
>services.sync.tokenServerURI = https://sync.myserver.ga/token/1.0/sync/1.5

where "myserver" is my own server

In syncserver.ini I have the following
>[server:main]
use = egg:gunicorn
host = 127.0.0.1
port = 5001
workers = 2
timeout = 60
[app:main]
use = egg:syncserver
[syncserver]
public_url = https://sync.myserver.ga
forwarded_allow_ips = *
force_wsgi_environ = false
sqluri = "mysql"
secret = "mykey"

in last two files I have hidden the real values.

And my nginx vhost file is:
>server {
    listen 443;
    ssl on;
    ssl_certificate     /etc/ssl/localcerts/myserver.pem;
    ssl_certificate_key /etc/ssl/localcerts/myserver.key;
    server_name sync.myserver.ga;
	location / {
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
                proxy_read_timeout 120;
                proxy_connect_timeout 10;
                proxy_pass http://127.0.0.1:5001/;
	        access_log      /var/log/nginx/sync.access.log;
	        error_log       /var/log/nginx/sync.error.log;
    }
}

I do not know why it works on the Desktop but not with your addon :(

Thanks in advance!

**Comment by ncalexan** [comment]
Hi!  Sorry I never replied to this.  This addon is deprecated now, so I won't be addressing this.  New documentation should be up at http://docs.services.mozilla.com/ shortly.  Hope you've gotten custom Sync working!
