### ISSUE TITLE
Unable to connect with Firefox 40.0.3

### ISSUE THREAD

**Issue by Olwaro** [ncalexan/fxa-custom-server-addon#6]
![screenshot_2015-09-19-19-38-46](https://cloud.githubusercontent.com/assets/477023/9977396/b0998840-5f06-11e5-93c0-8730d69bd750.png)

Sorry for the french localization. The error message says "Netwok connexion impossible".

My self-hosted syncserver is up an running, it works fine with my Firefox desktop.

Additionnal informations :
- Wifi is on
- Firefox version 40.0.3
- fxa-custome-server-addon version : 0.3
- Android version : 4.4.4

**Comment by ncalexan** [comment]
On Sat, Sep 19, 2015 at 1:52 PM, Olivier Hoarau <notifications@github.com>
wrote:

> [image: screenshot_2015-09-19-19-38-46]
> <https://cloud.githubusercontent.com/assets/477023/9977396/b0998840-5f06-11e5-93c0-8730d69bd750.png>
>
> Sorry for the french localization. The error message says "Netwok
> connexion impossible".
>
> My self-hosted syncserver is up an running, it works fine with my Firefox
> desktop.
>
> Additionnal informations :
>
>    - Wifi is on
>    - Firefox version 40.0.3
>    - fxa-custome-server-addon version : 0.3
>    - Android version : 4.4.4
>
> The endpoint "api-accounts.firefox.com/v1" looks like a typo -- that
should be "api.accounts.firefox.com/v1".  After that, |adb logcat| output
is needed.  See http://160.twinql.com/how-to-file-a-good-android-sync-bug/
for instructions.  Good luck!

**Comment by Olwaro** [comment]
Oops I have been tricked by the staging servers url "api-accounts.stage.mozaws.net/v1" with a dash.
It works now.

My aplogies for reporting a *non-*issue.

**Comment by ncalexan** [comment]
On Sun, Sep 20, 2015 at 7:49 AM, Olivier Hoarau <notifications@github.com>
wrote:

> Oops I have been tricked by the staging servers url "
> api-accounts.stage.mozaws.net/v1" with a dash.
> It works now.
>
> My aplogies for reporting a *non-*issue.
>
No trouble.  Always good to ask!
